export const CREATE = 'CREATE'
export const GET_ALL = 'GET_ALL'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const POST_LIKE = 'POST_LIKE'
export const AUTH = 'AUTH'
export const LOGOUT='LOGOUT'