export const CREATE = 'CREATE'
export const GET_ALL = 'GET_ALL'
export const GET_POST = 'GET_POST'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const POST_LIKE = 'POST_LIKE'
export const GET_BY_SEARCH = 'GET_BY_SEARCH'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const COMMENT = 'COMMENT'

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
